### ISSUE TITLE
Use pool of Pub/Sub connections to bypass per-connection 10 MB/s quota

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [GoogleCloudPlatform/pubsubbeat#35]
We (@gitlab) discovered an odd 10 MB/s limit on pubsubbeat, which we tracked down to [GCP Pub/Sub quota](https://cloud.google.com/pubsub/quotas), specifically this one:

> StreamingPull streams | 10 MB/s per open stream

It's possible to work around this quota by running multiple instances of pubsubbeat.

However, it would be nice if pubsubbeat had a mechanism for using a pool of Pub/Sub connections instead of just a single one.

**Comment by josephlewis42** [comment]
I'm adding a setting that I think should fix this. I have a PR out right now pending review. The GCP accounts I have access to may not reflect the same settings/options that are available publicly so I'd be grateful for help that the problem is fixed with the change. Once the PR gets approved, I'll create a pre-release and post another message here.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Thanks so much! We can definitely help with testing it out. :)

**Comment by josephlewis42** [comment]
Awesome, I have an RC built out now: https://github.com/GoogleCloudPlatform/pubsubbeat/releases/tag/1.3.0-rc

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
We tested this out and it appears to be working.

During our test case we quickly hit an unrelated bottleneck at ~14 MB/s, but the test proves that we are no longer hitting a 10 MB/s limit. I'd say this is good to go!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Closing this, since the 10 MB/s limit was addressed. :)
