### ISSUE TITLE
Pubsubbeat pull order

### ISSUE THREAD

**Issue by iv3rson76** [GoogleCloudPlatform/pubsubbeat#43]
After configuring pubsubbeat to pull mysql slow logs from GCP (Google Cloud Platform) that looks as following:
<img width="1060" alt="Screenshot 2020-05-04 at 11 58 32" src="https://user-images.githubusercontent.com/9348708/80950753-2418bf80-8dff-11ea-9a00-3f5131b5e0f3.png">

 I noticed that the order those log lines are being pulled is getting mixed and instead of being in the same order as they should be (filtered only the "textPayload" for better readibility):
![Screenshot 2020-05-04 at 12 05 04](https://user-images.githubusercontent.com/9348708/80950990-a43f2500-8dff-11ea-8b15-ee45302b7434.png)

I've checked the pubsubbeat configuration settings and the Google's Pub/Sub subscriptions and topics options but was unable to found a way to define the order log objects are being pulled so can you please clarify if there is option not to get mixed messages. Thanks!

**Comment by josephlewis42** [comment]
Pub/Sub makes some tradeoffs to achieve its high availability and throughput and unfortunately this is one of them. Depending on the amount of messages you may occasionally (or frequently) get messages out of order, and you may occasionally receive messages more than once because Pub/Sub errs on the side of caution by trying again if it can't guarantee a message was delivered.

Pub/Sub has some suggestions about [how to handle out of order messages](https://cloud.google.com/pubsub/docs/ordering). A common pattern is to sort and de-duplicate based on some key on the client side. I _think_ in Cloud Logging you'll be able to use the [`insertId` field](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) for deduplication and the timestamp for sorting.

I'm going to close this issue, but feel free to re-open or reach out if you have other questions. :-)
